### PR TITLE
Fix aggregations with text queries

### PR DESCRIPTION
**Pull request by MrEarle**
This aims to fix the bug referred to in #606.

First time contributing here, so please let me know if I'm missing something or I'm not up to your standards 😁.

### CODE REVIEW

**Comment by roman-right** [comment]
Hi @MrEarle ,
Thank you for the PR! Could you please take a look at tests? It looks like python3.7 is not supported

**Comment by MrEarle** [comment]
Oh, you're right! I'll fix it as soon as I have some time for it 👌🏼

**Comment by MrEarle** [comment]
Fixed the tests. I was using `list` for typing instead of `List`.

**Comment by roman-right** [comment]
Awesome! I'll play with it tomorrow and merge. Thank you!

**Review by roman-right — APPROVED** [review]

**Comment by roman-right** [comment]
Good job! And I like how you avoided Python comparison operations, as they are overridden.

**Pull request merged**
