### PR TITLE
Support for fetching deep-nested Links

### PR DESCRIPTION
**Pull request by csanders-rga**
Hi @roman-right!  Our team is trying to get Beanie to fetch deep-nested Links when `fetch_links=True`.  To accomplish this, I added additional queries to the MongoDB aggregation.  However, I saw your comments in the open issues related to nested Links, and I'm not sure this solution gets around the challenges you had mentioned.  Would super appreciate your feedback - thank you! :-)

### CODE REVIEW

**Comment by roman-right** [comment]
Hi @csanders-rga ,

Thank you very much for the PR. It looks good.
I'll check your implementation on Monday.

Linter shows some errors, could you please take a look? To check it locally you can use the git pre-commit rules attached to the repo.

**Comment by csanders-rga** [comment]
Hi @roman-right, I resolved the linter errors locally.  Please let me know if there's anything else I should adjust :-)

**Comment by roman-right** [comment]
Hi @csanders-rga ,
I'm sorry for the delay.
The code looks good. Could you please add the respective tests?

**Comment by csanders-rga** [comment]
Hi @roman-right, I updated the tests, please let me know what you think!

**Comment by roman-right** [comment]
Hey @csanders-rga 
Sorry for the late reply - busy time. I plan to check your PR and merge today-tomorrow.

**Comment by roman-right** [comment]
Hey @csanders-rga ,
Great job! Thank you for the PR. It is in `1.16.0` now

**Pull request merged**
