### PR TITLE
Feature: soft delete

### LINKED ISSUE #534: Soft Delete
### Discussed in https://github.com/roman-right/beanie/discussions/532

<div type='discussions-op-text'>

<sup>Originally posted by **N0odlez** April 13, 2023</sup>
Is it possible to have a Soft Delete functionality, or alternatively let me know how to add a Middleware on each database request to check if a field i.e "is_deleted" is equal to 1.

This would be useful as sometimes you dont want to actually delete the whole Document but you need to keep for auditing purposes.</div>

### PR DESCRIPTION
**Pull request by alm0ra**
Fixes #534 

in this PR i added new Document class with ability of soft delete

### CODE REVIEW

**Comment by roman-right** [comment]
Hi @alm0ra ,
Thank you for the PR. Could you please add tests for this?

**Comment by alm0ra** [comment]
@roman-right yes i can , but first i wanted to know is it ok to implement in this way? If it's ok i will add test

**Comment by alm0ra** [comment]
@roman-right 
i added test 
can you review?

**Comment by roman-right** [comment]
Merged,
It will be published today.

@alm0ra could you please add a doc page for this when you have time?

**Comment by alm0ra** [comment]
@roman-right 
Yeah , i will open a PR soon .

**Comment by jhamman** [comment]
This looks like a super cool feature. Are the docs in progress?

**Comment by alm0ra** [comment]
@jhamman 
I haven't started it yet.
But it has open issue

**Comment by yureiita** [comment]
Thank you for adding the feature. I tried the following and the soft delete works:
```python
doc1 = await SampleModel.find_one(SampleModel.id == id)
doc2 = await SampleModel.get(id)

await doc1.delete()
await doc2.delete()
```

However, when I tried the following, it hard delete instead of soft delete
```python
doc3 = await SampleModel.find_one(SampleModel.id == id).delete()
```

**Pull request merged**
