### PR TITLE
Refactor Encoder

### PR DESCRIPTION
**Pull request by gsakkis**
I took a stab at simplifying the `encoder` module a bit.

### CODE REVIEW

**Comment by roman-right** [comment]
Hi! Sorry for the delay.
I'll check this PR by the end of the week

**Comment by aksswami** [comment]
Can we merge this PR on priority? I am getting issue with Numpy array with beanie.

**Comment by roman-right** [comment]
Hey @gsakkis,
Sorry for the late reply. I had a lot of work to do to make Pydantic v2 work. It seems there are now many conflicts - it's hard to check. Could you please resolve them? Ping me on Discord once you've resolved them so I can get back to you faster.

**Comment by gsakkis** [comment]
@roman-right all conflicts have been resolved.

**Comment by roman-right** [comment]
Thank you! It will be published by the end of this week together with others

**Pull request merged**
