### PR TITLE
Feature/previous saved state

### PR DESCRIPTION
**Pull request by paul-finary**
Hi,

This PR tentatively adds a `_previous_saved_state`, which stores the `_saved_state` AFTER it has been updated because the changes have been persisted in the database.
This new state allows users to inspect the changes persisted to the database in an `after_event` callback, for example.
It adds new methods:
- `has_changed`
- `get_previous_saved_state()`
- `get_previous_changes()`

I also improved the documentation with examples of `is_changed`, `get_saved_state()`, `get_changes()`, and `rollback`.

Best,

### CODE REVIEW

**Comment by paul-finary** [comment]
@roman-right Can you have a look? Are you interested in this feature?

**Comment by paul-finary** [comment]
Tests are green again !

**Comment by roman-right** [comment]
Hey @paul-finary ,
Sorry for the delay. This feature looks interesting! Thank you!
As it can potentially increase RAM usage, could you please add a respective config to the settings with disabled by default?

**Comment by roman-right** [comment]
If I'll be slow about this PR again, pls ping me in Discord

**Comment by paul-finary** [comment]
> Hey @paul-finary , Sorry for the delay. This feature looks interesting! Thank you! As it can potentially increase RAM usage, could you please add a respective config to the settings with disabled by default?

Sure thing, I updated the PR!

**Comment by roman-right** [comment]
Merged. Thank you, @paul-finary !

**Pull request merged**
