### PR TITLE
Small addition to the Indexed function

### PR DESCRIPTION
**Pull request by jorants**
Small addition to the previous PR, Index now takes an optional argument to allow setting the index type. 
Sorry, i realized this would make sense to add a few minutes after you merged the previous one.

### CODE REVIEW

**Comment by roman-right** [comment]
Hi!
I like this :-) 

Could you please add a specific test with the non-default value (like in the example in the doc)? To have all the cases tested.

**Comment by jorants** [comment]
I have split up the tests and added one for a pymongo.TEXT argument.
To be more compatible with other versions of mongodb it only checks the key value, not the whole index structure.

**Review by roman-right — APPROVED** [review]
Looks good

**Comment by roman-right** [comment]
> I have split up the tests and added one for a pymongo.TEXT argument.
> To be more compatible with other versions of mongodb it only checks the key value, not the whole index structure.

Perfect. Looks very neat.
I will merge this guy a little later today or tomorrow.

**Pull request merged**
